name: Analizar calidad

on: push

jobs:
  analisis:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      
    steps:
      - name: Run pylint linter
        uses: advanced-security/python-lint-code-scanning-action@v1
        with:
          linter: pylint
